services:
  fastapi-microservice-pris:
    build:
      context: ../pris-backend
      dockerfile: ../docker/Dockerfile
    container_name: fastapi-microservice-pris
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    restart: always
    volumes:
      - ../pris-backend:/app
    depends_on:
      - postgres-pris

  postgres-pris:
    image: postgres:latest
    container_name: postgres-database-pris
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx-pris:
    image: nginx:latest
    container_name: nginx-frontend-pris
    restart: always
    ports:
      - "1006:80"
    volumes:
      - ../pris-front/dist:/usr/share/nginx/html
    depends_on:
      - fastapi-microservice-pris

volumes:
  postgres_data:
